# Generated by Django 4.1.7 on 2023-03-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imgLink', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('descr', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgLink', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('descr', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=50000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
